### ISSUE TITLE
hello :D

### ISSUE THREAD

**Issue by SSCBryce** [n-thumann/wg-nord#4]
It's giving me the same public/private key pair when I'm using different tokens and even different servers at the same time on Windows 11 (if that has anything to do with it)(all I did was extract the exe out of the zipped file and run it with the two parameters). Annoying... I need more than one config on the same server!

**Comment by Kanrinin-sama** [comment]
It just grabs from the API... why API give me same keys??? I need NEW CONFIGS!!!! :(

**Comment by n-thumann** [comment]
Hi, the private key is generated by NordVPN, so wg-nord has no influence over which private key is being returned :v:

**Comment by Kanrinin-sama** [comment]
Yeah sorry about that, I realized shortly after D:, but thanks. Weird that I grab new tokens, but it sends me the same stuff over and over...
